In [1]:
import pandas as pd
import numpy as np
from numpy.random import seed
seed(42)
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler


In [2]:
# Read in movie csv
movies = pd.read_csv("../Resources/imdb_final.csv")
movies.head()

imdb_title_id                  title  year    genre  duration country  \
0     tt0035423         Kate & Leopold  2001   Comedy       118     USA   
1     tt0113026        The Fantasticks  2000  Musical        86     USA   
2     tt0118589                Glitter  2001    Drama       104     USA   
3     tt0118652  The Attic Expeditions  2001   Comedy       100     USA   
4     tt0120467                 Vulgar  2000    Crime        87     USA   

             director           production_company    budget  total_votes  \
0       James Mangold              Konrad Pictures  48000000        75298   
1     Michael Ritchie  Michael Ritchie Productions  10000000         1082   
2  Vondie Curtis-Hall        Twentieth Century Fox  22000000        20959   
3       Jeremy Kasten      Tse Tse Fly Productions   1000000         1588   
4       Bryan Johnson           Chango Productions    120000         3852   

   ...  allover45  males  males18to29  males30to44  malesover45  females  \
0  ...        6.4    6.3          6.5          6.2          6.3      6.6   
1  ...        5.4    5.3          5.4          5.4          5.3      5.7   
2  ...        2.1    1.9          2.1          1.9          2.0      2.9   
3  ...        4.6    5.0          4.7          5.1          4.6      4.8   
4  ...        5.0    5.3          6.1          5.3          5.1      5.2   

   females18to29  females30to44  femalesover45  rating_class  
0            6.7            6.4            6.7          Good  
1            5.6            5.8            5.6          Good  
2            3.2            2.7            2.5           Bad  
3            5.8            4.6            4.6          Good  
4            5.2            5.3            4.6          Good  

[5 rows x 23 columns]

In [3]:
# Set values for X and y
X = movies[["year", "genre", "duration", "director", "budget"]]
y = movies["rating_class"].values.reshape(-1,1)
print(X.shape, y.shape)

(5060, 5) (5060, 1)


In [4]:
data = X.copy()
data

year    genre  duration            director    budget
0     2001   Comedy       118       James Mangold  48000000
1     2000  Musical        86     Michael Ritchie  10000000
2     2001    Drama       104  Vondie Curtis-Hall  22000000
3     2001   Comedy       100       Jeremy Kasten   1000000
4     2000    Crime        87       Bryan Johnson    120000
...    ...      ...       ...                 ...       ...
5055  2019   Comedy        84           Jon Lucas   5000000
5056  2019    Drama        94         Dan Sallitt     95000
5057  2019   Action        84        Glenn Miller    100000
5058  2019   Action        92        Keoni Waxman   3000000
5059  2019   Horror        77    Robin Entreinger    500000

[5060 rows x 5 columns]

In [5]:
# Dummy Encoding for genre column
data_binary_encoded = pd.get_dummies(data, columns= ["genre", "director"])
data_binary_encoded.head()

year  duration    budget  genre_Action  genre_Adventure  genre_Animation  \
0  2001       118  48000000             0                0                0   
1  2000        86  10000000             0                0                0   
2  2001       104  22000000             0                0                0   
3  2001       100   1000000             0                0                0   
4  2000        87    120000             0                0                0   

   genre_Biography  genre_Comedy  genre_Crime  genre_Drama  ...  \
0                0             1            0            0  ...   
1                0             0            0            0  ...   
2                0             0            0            1  ...   
3                0             1            0            0  ...   
4                0             0            1            0  ...   

   director_Zack Snyder  director_Zackary Adler  director_Zak Knutson  \
0                     0                       0                     0   
1                     0                       0                     0   
2                     0                       0                     0   
3                     0                       0                     0   
4                     0                       0                     0   

   director_Zak Penn  director_Zebediah De Soto  director_Zia Mojabi  \
0                  0                          0                    0   
1                  0                          0                    0   
2                  0                          0                    0   
3                  0                          0                    0   
4                  0                          0                    0   

   director_Ziad H. Hamzeh  director_Zoe Quist  director_Zoran Lisinac  \
0                        0                   0                       0   
1                        0                   0                       0   
2                        0                   0                       0   
3                        0                   0                       0   
4                        0                   0                       0   

   director_mink  
0              0  
1              0  
2              0  
3              0  
4              0  

[5 rows x 3537 columns]

In [45]:
# Create train/test split
X_train, X_test, y_train, y_test = train_test_split(data_binary_encoded, y, random_state=42)


In [46]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)
encoded_y_train

C:\Users\jewel\AppData\Local\Continuum\anaconda3\envs\PythonAdv\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


array([2, 2, 2, ..., 2, 2, 2])

In [53]:
rf = RandomForestClassifier(n_estimators = 50, max_features= 10, max_depth= 250, min_samples_split=20, max_samples=500)
rf = rf.fit(X_train, encoded_y_train)
print(f"Random Forest Training Score: {rf.score(X_train, encoded_y_train)}")
print(f"Random Forest Testing Score: {rf.score(X_test, encoded_y_test)}")

Random Forest Training Score: 0.7259552042160737
Random Forest Testing Score: 0.7059288537549407


In [34]:
importances = rf.feature_importances_
importances

array([0.04555907, 0.07173599, 0.07944987, ..., 0.        , 0.00059933,
       0.00036279])

In [35]:
sorted(zip(rf.feature_importances_, data_binary_encoded.columns))

[(0.0, 'director_Aaron J. Wiederspahn'),
 (0.0, 'director_Aaron Leong'),
 (0.0, 'director_Aaron Mirtes'),
 (0.0, 'director_Aaron Warren'),
 (0.0, 'director_Abe Sylvia'),
 (0.0, 'director_Adam Carolla'),
 (0.0, 'director_Adam Leon'),
 (0.0, 'director_Adam Meyerowitz'),
 (0.0, 'director_Adam Rodgers'),
 (0.0, 'director_Adam White'),
 (0.0, 'director_Adrian Corona'),
 (0.0, 'director_Adrian Pasdar'),
 (0.0, 'director_Adrienne Shelly'),
 (0.0, 'director_Aiden Dillard'),
 (0.0, 'director_Ajai'),
 (0.0, 'director_Akihiro Kitamura'),
 (0.0, 'director_Alain Desrochers'),
 (0.0, 'director_Alan Deutsch'),
 (0.0, 'director_Alan Rowe Kelly'),
 (0.0, 'director_Alex Erkiletian'),
 (0.0, 'director_Alex Keledjian'),
 (0.0, 'director_Alex Kurtzman'),
 (0.0, 'director_Allen C. Gardner'),
 (0.0, 'director_Allen Kellogg'),
 (0.0, 'director_Allen Wolf'),
 (0.0, 'director_Amy Talkington'),
 (0.0, 'director_Ana Lily Amirpour'),
 (0.0, 'director_Anders Anderson'),
 (0.0, 'director_Andrew Bowen'),
 (0.0, 'dire

In [38]:
encoded_predictions = rf.predict(X_test)
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

print(f"Predicted classes: {prediction_labels[:15]}")
print(f"Actual Labels: {y_test[:15]}")

Predicted classes: ['Good' 'Good' 'Good' 'Good' 'Good' 'Good' 'Good' 'Good' 'Good' 'Good'
 'Good' 'Good' 'Good' 'Good' 'Good']
Actual Labels: [['Good']
 ['Good']
 ['Excellent']
 ['Excellent']
 ['Good']
 ['Good']
 ['Good']
 ['Good']
 ['Good']
 ['Good']
 ['Excellent']
 ['Excellent']
 ['Excellent']
 ['Good']
 ['Good']]


In [39]:
# CLassification report
from sklearn.metrics import classification_report
print(classification_report(y_test, prediction_labels))

              precision    recall  f1-score   support

         Bad       0.70      0.31      0.43       270
   Excellent       0.65      0.09      0.16       167
        Good       0.71      0.96      0.81       828

    accuracy                           0.71      1265
   macro avg       0.69      0.45      0.47      1265
weighted avg       0.70      0.71      0.65      1265



In [40]:
# Confusion matrix
from sklearn.metrics import confusion_matrix as cm
cm(y_test, prediction_labels)

array([[ 85,   1, 184],
       [  8,  15, 144],
       [ 28,   7, 793]], dtype=int64)

## Grid Search

In [41]:
from sklearn.model_selection import GridSearchCV
n_estimators = [50, 150, 300]
max_features = [5, 10, 15]
max_depth = [10, 100, 200]
param_grid = dict(n_estimators=n_estimators, max_features=max_features, max_depth=max_depth)
grid = GridSearchCV(rf, param_grid, verbose=2, scoring = "accuracy")

In [42]:
grid.fit(X_train, np.ravel(encoded_y_train))

Fitting 5 folds for each of 27 candidates, totalling 135 fits
[CV] max_depth=10, max_features=5, n_estimators=50 ...................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] .... max_depth=10, max_features=5, n_estimators=50, total=   0.3s
[CV] max_depth=10, max_features=5, n_estimators=50 ...................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s


[CV] .... max_depth=10, max_features=5, n_estimators=50, total=   0.2s
[CV] max_depth=10, max_features=5, n_estimators=50 ...................
[CV] .... max_depth=10, max_features=5, n_estimators=50, total=   0.2s
[CV] max_depth=10, max_features=5, n_estimators=50 ...................
[CV] .... max_depth=10, max_features=5, n_estimators=50, total=   0.2s
[CV] max_depth=10, max_features=5, n_estimators=50 ...................
[CV] .... max_depth=10, max_features=5, n_estimators=50, total=   0.2s
[CV] max_depth=10, max_features=5, n_estimators=150 ..................
[CV] ... max_depth=10, max_features=5, n_estimators=150, total=   0.4s
[CV] max_depth=10, max_features=5, n_estimators=150 ..................
[CV] ... max_depth=10, max_features=5, n_estimators=150, total=   0.4s
[CV] max_depth=10, max_features=5, n_estimators=150 ..................
[CV] ... max_depth=10, max_features=5, n_estimators=150, total=   0.4s
[CV] max_depth=10, max_features=5, n_estimators=150 ..................
[CV] .

[Parallel(n_jobs=1)]: Done 135 out of 135 | elapsed:  6.9min finished


GridSearchCV(estimator=RandomForestClassifier(max_depth=250, max_features=10,
                                              n_estimators=50),
             param_grid={'max_depth': [10, 100, 200],
                         'max_features': [5, 10, 15],
                         'n_estimators': [50, 150, 300]},
             scoring='accuracy', verbose=2)

In [43]:
print(grid.best_params_)
print(grid.best_score_)

{'max_depth': 200, 'max_features': 15, 'n_estimators': 50}
0.696969696969697


## Save Model

In [28]:
import joblib
filename = 'rf.sav'
joblib.dump(rf, filename)


['rf.sav']